config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'
  resources :gossips
  get 'users/home', to: 'users#home'
   get 'users/login', to: 'users#login'
   post 'users/login', to: 'users#check'
   get 'users/deco', to: 'users#deco'
   get 'users/deconnection', to: 'users#deconnection'
    get 'users/new', to: 'users#new'
   post 'users/create', to: 'users#create'
   get 'users/profil', to: 'users#profil'
    get 'users/index', to: 'users#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossips = Gossip.new
    puts @gossips
  end

  def create
    if session[:user]
    @gossips = Gossip.create(users_id: session[:user][0]["id"],titre: params[:titre],content: params[:content])
    else
    redirect_to "/users/new"
    end
  end

  def edit
        @gossips = Gossip.find(params[:id])
  end

  def update
      @gossips = Gossip.find(params[:id])
      gossip_params = params.require(:gossip).permit(:titre, :content)
      @gossips.update(gossip_params)
      redirect_to gossips_path
    end

  def destroy
    @gossips = Gossip.find(params[:id])
    puts params
    @gossips.destroy
    redirect_to(gossips_path)
  end

  def index
    @gossips = Gossip.all
    @User = User.all
  end

  def show
    @gossips = Gossip.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def deco
     session[:user] = nil
     redirect_to '/users/deconnection'
   end
   def deconnection

   end

   def new
     @users = User.new
   end

   def create
     @user_params = params[:user]
     User.create(name: @user_params[:name], email: @user_params[:email], password: @user_params[:password])
     redirect_to '/users/login'
   end

   def index
     @all_user = User.all
   end

   def home
   end

   def login
   end

   def check
     @current_user = User.where(name: params[:name], email: params[:email], password: params[:password])
     if @current_user.where(name: params[:name], email: params[:email], password: params[:password]).exists?
       puts "Welcome back bro"
       flash[:info] = "Bienvenue #{@current_user} !"
       session[:user] = @current_user
       redirect_to "/users/home"
     else
       puts " Only members here, get out or register now ! "
       redirect_to "/users/login"
     end
   end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gossips/create.html.erb
<p>vous avez crée un article</p>

app/views/gossips/edit.html.erb
<%= form_for @gossips do |f| %>
  <div class="form-group">
    <p>speudo : <%= session[:user][0]["name"]%>!</p>
    <p>le id : <%= session[:user][0]["id"]%>!</p>
    <label>titre de l'article</label>
    <%= f.text_field :titre, class:'form-control' %>
  </div>
  <div class="form-group">
    <label>content de l'article</label>
    <%= f.text_area :content, class:'form-control' %>
  </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary">Modifier l'article</button>
      </div>
<% end %>

app/views/gossips/index.html.erb
<h1>La page des gossip </h1>
<p>
<a href="<%= new_gossip_path %>" class="btn btn-success">crée un gossip</a>
</p>
<% @gossips.each do |gossip| %>



  <p>
    <p>le id : <%= gossip.users_id%></p>

    <% if gossip.users_id  %>

    <p>speudo : <%= User.where(id: gossip.users_id)[0]["name"]%></p>

    <% end %>
    <p>le titre :<%=  gossip.titre %> ; le content:
    <%=  gossip.content%></p>
  <a href="<%=gossip_path(gossip.id)%>" class="btn btn-primary">lire la suite</a>
  <a href="<%=edit_gossip_path(gossip.id)%>" class="btn btn-default">editer</a>
  <a href="<%=gossip_path(gossip.id)%>" class="btn btn-danger">suprimer</a>
  </p>
<% end %>
<p>
<a href="<%= new_gossip_path %>" class="btn btn-success">crée un gossip</a>
</p>

app/views/gossips/new.html.erb
<form action="/gossips" method="POST">
  <p>titre</p>
  <input type="string" name="titre">
  <p>content</p>
  <input type="string" name="content"><br></br>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Envoyer le formulaire">
</form>

app/views/gossips/show.html.erb
<h1> <%= @gossips.titre %> </h1>
<h2> <%= @gossips.content %> </h2>
<p>
  <a href="<%=gossips_path%>" class="btn btn-primary">revenir sur les gossips</a>
  </p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '#' %></li>
        <li><%= link_to "Index des gossips",   '#' %></li>
        <li><%= link_to "Nouveau gossip", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/gossips/new">crée un gossip</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/gossips">voir les gossips <span class="sr-only">(current)</span></a>
          </li>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                 <% if session[:user] %>
                 <a class="nav-link" href="/users/deco">se deconnecter <span class="sr-only">(current)</span></a>
                 <% else %>
                 <a class="nav-link" href="/users/login">se connecter <span class="sr-only">(current)</span></a>
                <% end %>
               </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/new">crée un compte</a>
          </li>
      </div>
    </nav>
    <% if session[:user] %>
        <h4>Bienvenue  sur la page  <%= session[:user][0]["name"] %> !</h4>
       <h5>Tu es l'user n° <%= session[:user][0]["id"] %> sur cette page youpi !</h5>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/check.html.erb
<p>tu es logez </p>

app/views/users/deconnection.html.erb
<h1>vous êtes deconnecter</h1>

<a href="/users/home">Retourner à l'accueil</a>

app/views/users/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓 
  </h3>
  <%= link_to "Enregistre-toi !", '/users/new', class: "btn btn-lg btn-primary" %>
</div>

app/views/users/index.html.erb
<%= @all_user.each do |f| %>

<% f.name %>
<% f.email %>
<% f.password %>
<br/>

<% end %>

<br/>
<a href="/users/home">Retourner à l'accueil</a>

app/views/users/login.html.erb
<h1>LOGEZ VOUS</h1>
<%= form_tag "/users/login", method: :post do %>
  <input type="text" name="name" placeholder="name" /><br></br>
  <input type="text" name="email" placeholder="email" /><br></br>
  <input type="password" name="password" placeholder="password" /><br></br>
  <input type="submit" value="Se connecter"/>
<% end %>


<a href="/users/home">Retourner à l'accueil</a>

app/views/users/new.html.erb
<h1>CREER VOTRE COMPTE </h1>

<%= form_for @users, url: {action: "create"}  do |f| %>
Ton nom : <%= f.text_field :name %> <br />
Ton email <%= f.text_field :email %><br />
Ton mot de passe   <%= f.text_field :password %><br />
  <%= f.submit "create" %>
<% end %>

<a href="/user/login">se connecter</a><br></br>
<a href="/user/home">Retourner à l'accueil</a>

app/views/users/profil.html.erb
<p> Bienvenue  </p>
<%= session[:user] %>